.TH GHADOOP-ADD-NODES 1 LOCAL
.SH NAME
ghadoop-add-nodes \- Starts N new Hadoop node
.SH CONFIGURATION
Configuration is in /etc/gone/ec2.yaml in the YAML format.
See man page of
.B ghadoop-add-node
.SH USAGE
The tool takes an integer (N) as argument, lower than 20.
It calls ghadoop-add-node N times.
.SH AUTHOR
Olivier Sallou <olivier.sallou@irisa.fr>
.SH "SEE ALSO"
.BR ghadoop-add-node (1)



